[package]
name = "cris_tools_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
# ZeroMQ has trouble building on Windows gnu
#zmq = "0.10.0"
# So we use nng
nng = "1.0.1"
rfd = "0.14.1"
toml = "0.8.13"
serde = { version = "1.0", features = ["derive"] }